package structs

import (
	"time"
)

type User struct {
	ID        *string   `json:"id"`
	FirstName *string   `json:"first_name"`
	LastName  *string   `json:"last_name"`
	Email     *string   `json:"email"`
	Username  *string   `json:"username"`
	Password  *string   `json:"password"`
	CreatedAT time.Time `json:"created_at"`
}

type UserSpec struct {
	IncludeUsername bool
	IncludeEmail    bool
	IncludePassword bool
}

var EmailDomains = []string{
	"example.com", "test.com", "demo.com", "sample.com", "mail.com",
	"email.com", "domain.com", "webmail.com", "inbox.com", "myemail.com",
	"yahoo.com", "gmail.com", "hotmail.com", "aol.com", "outlook.com",
	"icloud.com", "protonmail.com", "zoho.com", "gmx.com", "yandex.com",
}

var FirstNames = []string{
	"Aaron", "Abigail", "Adam", "Adrian", "Adriana",
	"Aiden", "Alana", "Albert", "Alejandro", "Alex",
	"Alexa", "Alexander", "Alexandra", "Alexis", "Alice",
	"Alicia", "Alison", "Allen", "Allison", "Alyssa",
	"Amanda", "Amber", "Amelia", "Amy", "Ana",
	"Andrea", "Andrew", "Angela", "Ann", "Anna",
	"Anthony", "Antonio", "Aria", "Ariana", "Arthur",
	"Ashley", "Aubrey", "Audrey", "Austin", "Autumn",
	"Ava", "Avery", "Bailey", "Barbara", "Benjamin",
	"Beth", "Blake", "Bradley", "Brandon", "Brenda",
	"Brenna", "Brian", "Brianna", "Brittany", "Brooke",
	"Bruce", "Bryan", "Caleb", "Cameron", "Camille",
	"Carl", "Carlos", "Carmen", "Carol", "Caroline",
	"Carolyn", "Carter", "Cassandra", "Catherine", "Cecilia",
	"Charles", "Charlotte", "Chelsea", "Chloe", "Chris",
	"Christina", "Christine", "Christopher", "Cindy", "Claire",
	"Clara", "Clarence", "Clark", "Clayton", "Cody",
	"Cole", "Colin", "Colton", "Connor", "Corey",
	"Craig", "Crystal", "Curtis", "Cynthia", "Dakota",
	"Dale", "Dallas", "Daniel", "Daniela", "Danielle",
	"David", "Dawn", "Deborah", "Denise", "Dennis",
	"Derek", "Diana", "Diego", "Dominic", "Donald",
	"Donna", "Douglas", "Drew", "Dylan", "Edward",
	"Elena", "Elizabeth", "Ella", "Ellie", "Emily",
	"Emma", "Eric", "Erica", "Ethan", "Eva",
	"Evan", "Evelyn", "Faith", "Felicia", "Fernando",
	"Frank", "Gabriela", "Gabrielle", "Gary", "George",
	"Gerald", "Grace", "Grant", "Gregory", "Hannah",
	"Harper", "Harrison", "Hayden", "Heather", "Henry",
	"Holly", "Hunter", "Ian", "Isaac", "Isabella",
	"Isaiah", "Jacob", "Jacqueline", "James", "Jamie",
	"Jason", "Jasper", "Javier", "Jay", "Jeffrey",
	"Jennifer", "Jeremy", "Jesse", "Jessica", "Joel",
	"Jonathan", "Jordan", "Jose", "Joseph", "Joshua",
	"Juan", "Julia", "Julian", "Justin", "Karen",
	"Katherine", "Kathryn", "Katie", "Kayla", "Keith",
	"Kelly", "Kenneth", "Kevin", "Kimberly", "Kyle",
	"Laura", "Lauren", "Lawrence", "Leah", "Leo",
	"Leonard", "Liam", "Lillian", "Lily", "Linda",
	"Lisa", "Logan", "Louis", "Lucas", "Lucy",
	"Luis", "Luke", "Lydia", "Madison", "Marcus",
	"Margaret", "Maria", "Mark", "Martin", "Mary",
	"Mason", "Matthew", "Maya", "Megan", "Melanie",
	"Melissa", "Michael", "Michelle", "Miguel", "Mila",
	"Monica", "Morgan", "Nancy", "Natalie", "Nathan",
	"Nathaniel", "Nicole", "Noah", "Nora", "Olivia",
	"Oscar", "Owen", "Paige", "Pamela", "Patricia",
	"Patrick", "Paul", "Penelope", "Peter", "Philip",
	"Phoebe", "Rachel", "Raymond", "Rebecca", "Richard",
	"Riley", "Robert", "Roger", "Ronald", "Rosa",
	"Rose", "Ruby", "Russell", "Ryan", "Samantha",
	"Samuel", "Sandra", "Sara", "Sarah", "Scott",
	"Sean", "Sebastian", "Sergio", "Shane", "Shannon",
	"Sharon", "Shelby", "Sophia", "Spencer", "Stephanie",
	"Stephen", "Steven", "Summer", "Susan", "Sydney",
	"Taylor", "Teresa", "Thomas", "Timothy", "Tina",
	"Todd", "Trevor", "Tyler", "Valentina", "Vanessa",
	"Victoria", "Vincent", "Virginia", "Walter", "Wayne",
	"Wesley", "William", "Wyatt", "Xavier", "Zachary",
	"Zoe", "Zoey", "Abel", "Ace", "Adaline",
	"Adelaide", "Adeline", "Agnes", "Ainsley", "Alastair",
	"Alba", "Alberto", "Alec", "Alessandra", "Alessandro",
	"Alexei", "Alfie", "Alfonso", "Alfred", "Alina",
	"Alistair", "Allan", "Alma", "Alonso", "Alvaro",
	"Alvin", "Amara", "Ambrose", "Amira", "Amos",
	"Andre", "Andres", "Angelica", "Angelo", "Anita",
	"Annika", "Ansley", "Apollo", "Arabella", "Archer",
	"Archie", "Arden", "Ares", "Aria", "Ariel",
	"Arlo", "Armand", "Armando", "Arnold", "Artemis",
	"Asher", "Astrid", "Atlas", "Atticus", "August",
	"Augustus", "Aurora", "Axel", "Ayden", "Beatrice",
	"Beau", "Beckett", "Bella", "Bennett", "Benson",
	"Bernard", "Bianca", "Billy", "Bodhi", "Boris",
	"Brady", "Bram", "Brayden", "Brendan", "Brett",
	"Bruno", "Buck", "Callum", "Calvin", "Camden",
	"Candace", "Cara", "Cari", "Carla", "Carlie",
	"Cason", "Cassidy", "Cassius", "Cayden", "Cecil",
	"Cedric", "Celeste", "Cesar", "Chase", "Chester",
	"Cheyenne", "Chiara", "Chip", "Christian", "Clarence",
	"Claude", "Claudia", "Clementine", "Clifford", "Clifton",
	"Clint", "Clive", "Colby", "Conrad", "Cordelia",
	"Corinne", "Cornelius", "Courtney", "Crew", "Cruz",
}

var LastNames = []string{
	"Abbott", "Adams", "Aguilar", "Alexander", "Allen",
	"Alvarez", "Anderson", "Andrews", "Armstrong", "Arnold",
	"Austin", "Bailey", "Baker", "Barnes", "Barrett",
	"Bell", "Bennett", "Bishop", "Black", "Blair",
	"Blake", "Boyd", "Bradley", "Brady", "Brooks",
	"Brown", "Bryant", "Burke", "Burns", "Butler",
	"Byrd", "Campbell", "Cannon", "Carpenter", "Carroll",
	"Carter", "Castro", "Chavez", "Clark", "Cole",
	"Coleman", "Collins", "Cook", "Cooper", "Cox",
	"Crawford", "Cruz", "Cunningham", "Curtis", "Daniels",
	"Davidson", "Davis", "Dawson", "Day", "Dean",
	"Diaz", "Dixon", "Doe", "Douglas", "Duncan",
	"Dunn", "Edwards", "Elliott", "Ellis", "Evans",
	"Ferguson", "Fernandez", "Fields", "Fisher", "Fleming",
	"Fletcher", "Flores", "Ford", "Foster", "Fox",
	"Franklin", "Freeman", "Fuller", "Garcia", "Gardner",
	"Garrett", "Gibson", "Gomez", "Gonzalez", "Gordon",
	"Graham", "Grant", "Gray", "Green", "Greene",
	"Gregory", "Griffin", "Guerrero", "Gutierrez", "Hall",
	"Hamilton", "Hansen", "Harris", "Harrison", "Hart",
	"Harvey", "Hawkins", "Hayes", "Henderson", "Henry",
	"Hernandez", "Hill", "Hoffman", "Holmes", "Howard",
	"Hughes", "Hunt", "Hunter", "Jackson", "Jacobs",
	"James", "Jenkins", "Jensen", "Johnson", "Johnston",
	"Jones", "Jordan", "Kelly", "Kennedy", "Kim",
	"King", "Knight", "Lambert", "Lane", "Larson",
	"Lawrence", "Lee", "Lewis", "Long", "Lopez",
	"Lynch", "Marshall", "Martin", "Martinez", "Mason",
	"Matthews", "McCarthy", "McDonald", "McKinney", "Medina",
	"Meyer", "Miller", "Mills", "Mitchell", "Moore",
	"Morales", "Morgan", "Morris", "Morrison", "Murphy",
	"Murray", "Myers", "Nelson", "Newman", "Nguyen",
	"Nichols", "Norris", "Oliver", "Olson", "Ortiz",
	"Owen", "Owens", "Palmer", "Parker", "Patterson",
	"Perez", "Perry", "Peters", "Peterson", "Phillips",
	"Pierce", "Porter", "Powell", "Price", "Ramirez",
	"Ramos", "Reed", "Reid", "Reynolds", "Rhodes",
	"Rice", "Richards", "Richardson", "Riley", "Rivera",
	"Roberts", "Robertson", "Robinson", "Rodriguez", "Rogers",
	"Ross", "Russell", "Ryan", "Sanchez", "Sanders",
	"Schmidt", "Scott", "Shaw", "Simmons", "Simpson",
	"Smith", "Snyder", "Soto", "Spencer", "Stanley",
	"Stephens", "Stevens", "Stewart", "Stone", "Sullivan",
	"Sutton", "Taylor", "Thomas", "Thompson", "Torres",
	"Tucker", "Turner", "Walker", "Wallace", "Walsh",
	"Ward", "Warren", "Washington", "Watson", "Weaver",
	"Webb", "Wells", "West", "White", "Williams",
	"Wilson", "Wood", "Woods", "Wright", "Young",
	"Acosta", "Adkins", "Allison", "Alston", "Barber",
	"Barker", "Barlow", "Barnett", "Barton", "Bass",
	"Bates", "Bauer", "Baxter", "Benson", "Bentley",
	"Berg", "Berger", "Berman", "Bernard", "Bowers",
	"Bowen", "Bowman", "Brennan", "Briggs", "Brinkman",
	"Brock", "Browning", "Buchanan", "Burgess", "Calhoun",
	"Callahan", "Cameron", "Campos", "Cantu", "Cardenas",
	"Carey", "Carlson", "Carson", "Case", "Casey",
	"Castillo", "Cervantes", "Chambers", "Chan", "Chang",
	"Chapman", "Chase", "Chen", "Christensen", "Christian",
	"Church", "Cisneros", "Clements", "Cleveland", "Cobb",
	"Cochran", "Cohen", "Conner", "Conrad", "Contreras",
	"Conway", "Cooke", "Copeland", "Cortez", "Craig",
	"Crane", "Cross", "Dalton", "Daugherty", "Delgado",
	"Dennis", "Dillon", "Dominguez", "Donaldson", "Donovan",
	"Dougherty", "Doyle", "Drake", "Duffy", "Dunbar",
	"Dunlap", "Duran", "Durham", "Dyer", "Eaton",
	"Erickson", "Espinoza", "Estrada", "Farley", "Farmer",
	"Farrell", "Faulkner", "Figueroa", "Finley", "Fischer",
	"Fitzgerald", "Floyd", "Flynn", "Forbes", "Fowler",
	"Francis", "Frazier", "French", "Frost", "Gallagher",
	"Garner", "Garza", "Gay", "George", "Gilbert",
	"Gill", "Glover", "Golden", "Goodman", "Goodwin",
	"Graves", "Griffith", "Grimes", "Gross", "Guerra",
	"Hale", "Haley", "Hampton", "Hardy", "Harmon",
	"Harper", "Harrington", "Hartman", "Hatcher", "Hawkins",
	"Haynes", "Heath", "Hicks", "Higgins", "Hines",
	"Holt", "Hood", "Hoover", "Hopkins", "Horn",
	"Horne", "Horton", "House", "Houston", "Hudson",
	"Huffman", "Humphrey", "Hutchinson", "Ingram", "Irwin",
	"Ito", "Jimenez", "Johns", "Joyce", "Juarez",
	"Kane", "Kaufman", "Keith", "Kelley", "Kendall",
	"Kent", "Kerr", "Kirk", "Klein", "Knox",
	"Koch", "Kramer", "Lamb", "Lang", "Lara",
	"Lawson", "Lester", "Levy", "Lowe", "Lozano",
	"Luna", "Mack", "Madden", "Mahoney", "Mann",
	"Manning", "Marks", "Marsh", "Mata", "Maxwell",
	"McBride", "McCoy", "McCullough", "McDowell", "McFarland",
	"McGee", "McKenzie", "McLaughlin", "McMahon", "McMillan",
	"McNeil", "Melton", "Mendez", "Mendoza", "Merritt",
	"Miles", "Miranda", "Molina", "Monroe", "Montoya",
	"Moon", "Moran", "Morrow", "Moser", "Moss",
	"Mullins", "Munoz", "Nash", "Neal", "Nguyen",
	"Noble", "Noel", "Nolan", "Norman", "Norton",
	"Nunez", "Oconner", "Odell", "Odom", "Orozco",
}

var CommonWords = []string{
	"apple", "arrow", "anchor", "angel", "autumn",
	"breeze", "bridge", "bright", "brave", "blade",
	"castle", "candle", "cloud", "crown", "creek",
	"delta", "dawn", "dagger", "drift", "dream",
	"ember", "eagle", "earth", "elder", "echo",
	"flame", "frost", "forge", "field", "flash",
	"garden", "glacier", "gloom", "grace", "gravel",
	"harbor", "haven", "hollow", "honey", "horizon",
	"island", "iron", "ivory", "inlet", "impact",
	"jungle", "jewel", "jasper", "journey", "justice",
	"kindle", "knell", "kelp", "kestrel", "kernel",
	"lantern", "lemon", "linen", "lotus", "lumber",
	"marble", "meadow", "mirror", "mist", "moss",
	"nectar", "needle", "noble", "north", "night",
	"ocean", "onyx", "orbit", "olive", "origin",
	"pebble", "pine", "prism", "petal", "pearl",
	"quartz", "quest", "quill", "quarry", "quick",
	"river", "ridge", "rain", "robin", "rune",
	"silver", "storm", "smoke", "stone", "stream",
	"timber", "tide", "torch", "thorn", "trail",
	"ultra", "umbra", "uplift", "union", "urban",
	"valley", "vapor", "veil", "violet", "vine",
	"water", "willow", "winter", "wave", "wind",
	"xenon", "xylem", "xerus", "xeric", "xanth",
	"yellow", "yonder", "youth", "yarn", "yield",
	"zenith", "zephyr", "zinc", "zone", "zeal",
	"acorn", "amber", "anvil", "arch", "ash",
	"basin", "beam", "bell", "birch", "blaze",
	"cedar", "chalk", "cliff", "cobalt", "comet",
	"dew", "dome", "door", "drake", "dust",
	"edge", "elm", "epoch", "ether", "eve",
	"fern", "fig", "flint", "foam", "ford",
	"gate", "gem", "glade", "glen", "gust",
	"haze", "heath", "hedge", "helm", "hemp",
	"ice", "idol", "inch", "indigo", "isle",
	"jade", "jam", "jar", "jaw", "jest",
	"key", "kin", "kit", "knot", "kraft",
	"lake", "lark", "latch", "laurel", "leaf",
	"mace", "malt", "mane", "maple", "marsh",
	"nave", "nest", "newt", "nimbus", "node",
	"oak", "oar", "opal", "ore", "oven",
	"pack", "palm", "path", "peak", "pine",
	"rack", "raft", "rake", "reed", "reef",
	"sable", "sage", "salt", "sand", "shard",
	"teak", "teal", "thorn", "tile", "tin",
	"vale", "vault", "vein", "vest", "void",
	"wade", "wand", "ward", "weld", "wren",
	"yard", "yew", "yolk", "yon", "yucca",
}

var Animals = []string{
	"albatross", "alligator", "alpaca", "anaconda", "antelope",
	"armadillo", "axolotl", "baboon", "badger", "barracuda",
	"bat", "bear", "beaver", "bison", "boar",
	"bobcat", "buffalo", "bull", "butterfly", "camel",
	"capybara", "caracal", "caribou", "cassowary", "cheetah",
	"chipmunk", "cobra", "condor", "cougar", "coyote",
	"crane", "crocodile", "crow", "dingo", "dolphin",
	"donkey", "dormouse", "dragonfly", "duck", "eagle",
	"eel", "elephant", "elk", "falcon", "ferret",
	"flamingo", "fox", "frog", "gazelle", "gecko",
	"giraffe", "gnu", "goat", "goose", "gorilla",
	"grizzly", "groundhog", "hamster", "hare", "hawk",
	"hedgehog", "heron", "hippo", "hornet", "horse",
	"hound", "hyena", "ibex", "iguana", "impala",
	"jackal", "jaguar", "jellyfish", "kangaroo", "koala",
	"komodo", "kookaburra", "lamprey", "lemur", "leopard",
	"lion", "lizard", "llama", "lobster", "lynx",
	"magpie", "mamba", "manatee", "meerkat", "mink",
	"mongoose", "monitor", "moose", "moth", "mule",
	"narwhal", "newt", "nighthawk", "ocelot", "octopus",
	"opossum", "osprey", "ostrich", "otter", "owl",
	"ox", "panda", "panther", "parrot", "pelican",
	"penguin", "porcupine", "porpoise", "puma", "python",
	"quail", "quokka", "rabbit", "raccoon", "raven",
	"rhino", "roadrunner", "salamander", "salmon", "scorpion",
	"seahorse", "seal", "shark", "skunk", "sloth",
	"snail", "snake", "sparrow", "spider", "squid",
	"squirrel", "stag", "stallion", "starling", "stingray",
	"stoat", "stork", "swan", "tapir", "tarantula",
	"tiger", "toad", "tortoise", "toucan", "turkey",
	"turtle", "viper", "vulture", "walrus", "warthog",
	"wasp", "weasel", "whale", "wildcat", "wolf",
	"wolverine", "wombat", "woodpecker", "yak", "zebra",
	"zebu", "zorilla", "zorro", "aardvark", "addax",
	"agama", "aye-aye", "binturong", "bongo", "booby",
	"bushbuck", "canary", "caracara", "catfish", "chaffinch",
	"chamois", "chevrotain", "chinchilla", "civet", "coypu",
	"curlew", "dhole", "dikdik", "dugong", "dunlin",
	"echidna", "finch", "fossa", "frigatebird", "galago",
}

var AbstractWords = []string{
	"abyss", "aegis", "aeon", "aftermath", "agency",
	"alchemy", "allure", "amnesia", "anarchy", "apex",
	"arcane", "ardor", "aura", "axiom", "azure",
	"balance", "blight", "bliss", "bounty", "burden",
	"calm", "catalyst", "chaos", "cipher", "clarity",
	"cosmos", "courage", "craft", "creed", "crimson",
	"dark", "decay", "deep", "defiance", "depth",
	"desire", "destiny", "dread", "drive", "dusk",
	"enigma", "entropy", "envy", "epoch", "essence",
	"eternity", "euphoria", "exile", "existance", "expanse",
	"facade", "fate", "fervor", "flaw", "flux",
	"focus", "folly", "force", "frenzy", "fury",
	"ghost", "glitch", "glory", "gloom", "grace",
	"greed", "grief", "grit", "growth", "guile",
	"havoc", "heart", "hope", "hubris", "hunger",
	"husk", "hymn", "ideal", "illusion", "impulse",
	"inertia", "infinity", "instinct", "intent", "irony",
	"karma", "kinship", "legend", "limbo", "logic",
	"loss", "luck", "lure", "lust", "malice",
	"mania", "memory", "mercy", "might", "mind",
	"mirage", "moment", "momentum", "myth", "nemesis",
	"nexus", "nihil", "oblivion", "obsession", "omen",
	"oracle", "order", "paradox", "passion", "pattern",
	"peace", "peril", "phantom", "power", "pride",
	"prism", "psyche", "purpose", "rage", "rapture",
	"reason", "reckoning", "refuge", "regret", "reign",
	"remnant", "resolve", "rift", "ruin", "sanctum",
	"serenity", "shadow", "shame", "signal", "silence",
	"sin", "solace", "sorrow", "soul", "spark",
	"specter", "spite", "strife", "struggle", "sublime",
	"surge", "swarm", "symbol", "synergy", "tempest",
	"tension", "terror", "theory", "thought", "threshold",
	"time", "torment", "trauma", "trial", "triumph",
	"truth", "twilight", "unknown", "valor", "vanity",
	"vengeance", "virtue", "vision", "void", "vortex",
	"wander", "wrath", "zenith", "zeal", "zero",
	"animus", "apathy", "ardour", "bleak", "breach",
	"cadence", "calamity", "candor", "cascade", "chasm",
	"clamor", "clash", "collapse", "comet", "command",
	"complex", "conflict", "control", "convergence", "conviction",
	"corona", "covenant", "crux", "culmination", "cunning",
}

var SafeSymbols = []string{
	".", "-", "_", "!", "#", "$", "%", "^",
}

var SafeUsernameSymbols = []string{
	"-", "_",
}

var SafeEmailSymbols = []string{
	".", "-", "_",
}

type Person struct {
	Firstname string
	Lastname  string
	Email     string
	Username  string
	Password  string
}
